FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=changeme
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV GENERIC_TIMEZONE=Europe/Moscow
ENV WEBHOOK_URL=https://RENDER_URL
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV N8N_ENCRYPTION_KEY=renderkey123456

EXPOSE 5678
ENTRYPOINT ["n8n"]
CMD ["start"]
